### ISSUE TITLE
Getting JacksonConverterFactory error

### ISSUE THREAD

**Issue by lrivera8** [upnext/BeaconControl_Android_SDK#8]
Getting java.lang.IncompatibleClassChangeError: com.upnext.beaconos.sdk.backend.JacksonConverterFactory when BeaconSDK.getInstance().

Logs:

05-02 17:10:32.761     I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.upnext.beaconos.sdk.backend.JacksonConverterFactory>
05-02 17:10:32.761     I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.upnext.beaconos.sdk.backend.JacksonConverterFactory>
05-02 17:10:32.785     I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<com.upnext.beaconos.sdk.backend.JacksonConverterFactory>
05-02 17:10:32.785     D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
05-02 17:10:32.802     E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.cirici.androidbase, PID: 3875
    java.lang.IncompatibleClassChangeError: com.upnext.beaconos.sdk.backend.JacksonConverterFactory
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.getRetrofitInstance(BeaconControlManagerImpl.java:93)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.<init>(BeaconControlManagerImpl.java:68)
            at com.upnext.beaconos.sdk.backend.BeaconControlManagerImpl.getInstance(BeaconControlManagerImpl.java:49)
            at com.upnext.beaconos.sdk.BeaconSDK.getBeaconSDKInstance(BeaconSDK.java:80)
            at com.upnext.beaconos.sdk.BeaconSDK.getInstance(BeaconSDK.java:70)
            at com.cirici.beacons.MainActivity.onCreate(MainActivity.java:182)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by lrivera8** [comment]
I have been checking and it happens when I am using retrofit on my project aswell.

Any ideas?

Thank you.

**Comment by roman-upnext** [comment]
JacksonConverterFactory will be removed in the upcoming new version of the library, which makes this bug obsolete. If you find a similar problem please open a new issue.
